module Rfaker
  class FakerTree
    attr_accessor tree: Hash[String, Array[untyped]]

    def arbitrary_substitutions: -> Hash[String, String]

    def arity_pruned_meth_adder: -> Array[Method]

    def build_full_call: -> String

    def call_fixer: -> String

    def camelise: -> String

    def directory_hash: -> Hash[String, untyped]

    def directory_hash_iterator: -> [String | Hash[untyped, untyped]]

    def enumerate_fclass_methods: -> [String, Array[Method]]

    def method_adder: -> Array[Method]

  end
end
